// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"mime/multipart"

	"github.com/Gergenus/bookingService/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEquipmentServiceInterface creates a new instance of MockEquipmentServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEquipmentServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEquipmentServiceInterface {
	mock := &MockEquipmentServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEquipmentServiceInterface is an autogenerated mock type for the EquipmentServiceInterface type
type MockEquipmentServiceInterface struct {
	mock.Mock
}

type MockEquipmentServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEquipmentServiceInterface) EXPECT() *MockEquipmentServiceInterface_Expecter {
	return &MockEquipmentServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateEquipment provides a mock function for the type MockEquipmentServiceInterface
func (_mock *MockEquipmentServiceInterface) CreateEquipment(ctx context.Context, equipment models.Equipment, image *multipart.FileHeader) (int, error) {
	ret := _mock.Called(ctx, equipment, image)

	if len(ret) == 0 {
		panic("no return value specified for CreateEquipment")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Equipment, *multipart.FileHeader) (int, error)); ok {
		return returnFunc(ctx, equipment, image)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Equipment, *multipart.FileHeader) int); ok {
		r0 = returnFunc(ctx, equipment, image)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Equipment, *multipart.FileHeader) error); ok {
		r1 = returnFunc(ctx, equipment, image)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEquipmentServiceInterface_CreateEquipment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEquipment'
type MockEquipmentServiceInterface_CreateEquipment_Call struct {
	*mock.Call
}

// CreateEquipment is a helper method to define mock.On call
//   - ctx context.Context
//   - equipment models.Equipment
//   - image *multipart.FileHeader
func (_e *MockEquipmentServiceInterface_Expecter) CreateEquipment(ctx interface{}, equipment interface{}, image interface{}) *MockEquipmentServiceInterface_CreateEquipment_Call {
	return &MockEquipmentServiceInterface_CreateEquipment_Call{Call: _e.mock.On("CreateEquipment", ctx, equipment, image)}
}

func (_c *MockEquipmentServiceInterface_CreateEquipment_Call) Run(run func(ctx context.Context, equipment models.Equipment, image *multipart.FileHeader)) *MockEquipmentServiceInterface_CreateEquipment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Equipment
		if args[1] != nil {
			arg1 = args[1].(models.Equipment)
		}
		var arg2 *multipart.FileHeader
		if args[2] != nil {
			arg2 = args[2].(*multipart.FileHeader)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEquipmentServiceInterface_CreateEquipment_Call) Return(n int, err error) *MockEquipmentServiceInterface_CreateEquipment_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockEquipmentServiceInterface_CreateEquipment_Call) RunAndReturn(run func(ctx context.Context, equipment models.Equipment, image *multipart.FileHeader) (int, error)) *MockEquipmentServiceInterface_CreateEquipment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEquipment provides a mock function for the type MockEquipmentServiceInterface
func (_mock *MockEquipmentServiceInterface) DeleteEquipment(ctx context.Context, equipment_id int) error {
	ret := _mock.Called(ctx, equipment_id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEquipment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, equipment_id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEquipmentServiceInterface_DeleteEquipment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEquipment'
type MockEquipmentServiceInterface_DeleteEquipment_Call struct {
	*mock.Call
}

// DeleteEquipment is a helper method to define mock.On call
//   - ctx context.Context
//   - equipment_id int
func (_e *MockEquipmentServiceInterface_Expecter) DeleteEquipment(ctx interface{}, equipment_id interface{}) *MockEquipmentServiceInterface_DeleteEquipment_Call {
	return &MockEquipmentServiceInterface_DeleteEquipment_Call{Call: _e.mock.On("DeleteEquipment", ctx, equipment_id)}
}

func (_c *MockEquipmentServiceInterface_DeleteEquipment_Call) Run(run func(ctx context.Context, equipment_id int)) *MockEquipmentServiceInterface_DeleteEquipment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEquipmentServiceInterface_DeleteEquipment_Call) Return(err error) *MockEquipmentServiceInterface_DeleteEquipment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEquipmentServiceInterface_DeleteEquipment_Call) RunAndReturn(run func(ctx context.Context, equipment_id int) error) *MockEquipmentServiceInterface_DeleteEquipment_Call {
	_c.Call.Return(run)
	return _c
}

// Equipment provides a mock function for the type MockEquipmentServiceInterface
func (_mock *MockEquipmentServiceInterface) Equipment(ctx context.Context, equipment_id int) (*models.Equipment, error) {
	ret := _mock.Called(ctx, equipment_id)

	if len(ret) == 0 {
		panic("no return value specified for Equipment")
	}

	var r0 *models.Equipment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*models.Equipment, error)); ok {
		return returnFunc(ctx, equipment_id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *models.Equipment); ok {
		r0 = returnFunc(ctx, equipment_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Equipment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, equipment_id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEquipmentServiceInterface_Equipment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Equipment'
type MockEquipmentServiceInterface_Equipment_Call struct {
	*mock.Call
}

// Equipment is a helper method to define mock.On call
//   - ctx context.Context
//   - equipment_id int
func (_e *MockEquipmentServiceInterface_Expecter) Equipment(ctx interface{}, equipment_id interface{}) *MockEquipmentServiceInterface_Equipment_Call {
	return &MockEquipmentServiceInterface_Equipment_Call{Call: _e.mock.On("Equipment", ctx, equipment_id)}
}

func (_c *MockEquipmentServiceInterface_Equipment_Call) Run(run func(ctx context.Context, equipment_id int)) *MockEquipmentServiceInterface_Equipment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEquipmentServiceInterface_Equipment_Call) Return(equipment *models.Equipment, err error) *MockEquipmentServiceInterface_Equipment_Call {
	_c.Call.Return(equipment, err)
	return _c
}

func (_c *MockEquipmentServiceInterface_Equipment_Call) RunAndReturn(run func(ctx context.Context, equipment_id int) (*models.Equipment, error)) *MockEquipmentServiceInterface_Equipment_Call {
	_c.Call.Return(run)
	return _c
}

// EquipmentByName provides a mock function for the type MockEquipmentServiceInterface
func (_mock *MockEquipmentServiceInterface) EquipmentByName(ctx context.Context, equipmentName string) ([]models.Equipment, error) {
	ret := _mock.Called(ctx, equipmentName)

	if len(ret) == 0 {
		panic("no return value specified for EquipmentByName")
	}

	var r0 []models.Equipment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.Equipment, error)); ok {
		return returnFunc(ctx, equipmentName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.Equipment); ok {
		r0 = returnFunc(ctx, equipmentName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Equipment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, equipmentName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEquipmentServiceInterface_EquipmentByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EquipmentByName'
type MockEquipmentServiceInterface_EquipmentByName_Call struct {
	*mock.Call
}

// EquipmentByName is a helper method to define mock.On call
//   - ctx context.Context
//   - equipmentName string
func (_e *MockEquipmentServiceInterface_Expecter) EquipmentByName(ctx interface{}, equipmentName interface{}) *MockEquipmentServiceInterface_EquipmentByName_Call {
	return &MockEquipmentServiceInterface_EquipmentByName_Call{Call: _e.mock.On("EquipmentByName", ctx, equipmentName)}
}

func (_c *MockEquipmentServiceInterface_EquipmentByName_Call) Run(run func(ctx context.Context, equipmentName string)) *MockEquipmentServiceInterface_EquipmentByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEquipmentServiceInterface_EquipmentByName_Call) Return(equipments []models.Equipment, err error) *MockEquipmentServiceInterface_EquipmentByName_Call {
	_c.Call.Return(equipments, err)
	return _c
}

func (_c *MockEquipmentServiceInterface_EquipmentByName_Call) RunAndReturn(run func(ctx context.Context, equipmentName string) ([]models.Equipment, error)) *MockEquipmentServiceInterface_EquipmentByName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEquipment provides a mock function for the type MockEquipmentServiceInterface
func (_mock *MockEquipmentServiceInterface) UpdateEquipment(ctx context.Context, equipment models.Equipment) error {
	ret := _mock.Called(ctx, equipment)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEquipment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Equipment) error); ok {
		r0 = returnFunc(ctx, equipment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEquipmentServiceInterface_UpdateEquipment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEquipment'
type MockEquipmentServiceInterface_UpdateEquipment_Call struct {
	*mock.Call
}

// UpdateEquipment is a helper method to define mock.On call
//   - ctx context.Context
//   - equipment models.Equipment
func (_e *MockEquipmentServiceInterface_Expecter) UpdateEquipment(ctx interface{}, equipment interface{}) *MockEquipmentServiceInterface_UpdateEquipment_Call {
	return &MockEquipmentServiceInterface_UpdateEquipment_Call{Call: _e.mock.On("UpdateEquipment", ctx, equipment)}
}

func (_c *MockEquipmentServiceInterface_UpdateEquipment_Call) Run(run func(ctx context.Context, equipment models.Equipment)) *MockEquipmentServiceInterface_UpdateEquipment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Equipment
		if args[1] != nil {
			arg1 = args[1].(models.Equipment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEquipmentServiceInterface_UpdateEquipment_Call) Return(err error) *MockEquipmentServiceInterface_UpdateEquipment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEquipmentServiceInterface_UpdateEquipment_Call) RunAndReturn(run func(ctx context.Context, equipment models.Equipment) error) *MockEquipmentServiceInterface_UpdateEquipment_Call {
	_c.Call.Return(run)
	return _c
}
